<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="MAIN" Id="{9d96564e-b6fd-4974-a561-8c23fb6018b6}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	Position1:INT;
	Position2:INT;
	Position3:INT;
	MyMashine:Mashine;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[MyMashine();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>