<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="Sensore" Id="{525d2913-fde5-4615-bba6-751e7012095e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Sensore
VAR_INPUT
	i_i_SensorePosition	:	INT;
	i_b_SensoreActive		:	BOOL;
END_VAR

]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>